name: CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: Format
        run: cargo fmt --check
      - name: Build
        run: cargo build --all-targets
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test
      - name: Doc
        run: cargo doc --no-deps
